package com.whiterabbit.postmanlibsample;

import android.content.Context;
import android.os.Parcel;
import com.whiterabbit.postman.commands.RestServerCommand;
import com.whiterabbit.postman.commands.ResultParseException;
import org.scribe.model.OAuthRequest;
import org.scribe.model.Verb;

/**
 * Created with IntelliJ IDEA.
 * User: fedepaol
 * Date: 12/18/12
 * Time: 12:41 AM
 */
public class SampleRestOAuthCommand extends RestServerCommand {


    public SampleRestOAuthCommand(String url){
        super(Verb.GET, url);
    }

    @Override
    protected void processHttpResult(String result, Context context) throws ResultParseException {
        //TODO Autogenerated
    }

    @Override
    protected void addParamsToRequest(OAuthRequest request) {
        //TODO Autogenerated
    }

    @Override
    public int describeContents() {
        return 0;  //TODO Autogenerated
    }



    public static final Creator<SampleRestOAuthCommand> CREATOR
            = new Creator<SampleRestOAuthCommand>() {
        public SampleRestOAuthCommand createFromParcel(Parcel in) {
            return new SampleRestOAuthCommand(in);
        }

        public SampleRestOAuthCommand[] newArray(int size) {
            return new SampleRestOAuthCommand[size];
        }
    };


    public SampleRestOAuthCommand(Parcel in){
        super(in);
    }

}
