package com.whiterabbit.postmanlibsample;

import android.content.Context;
import android.os.Parcel;
import android.os.Parcelable;
import android.util.Log;
import com.whiterabbit.postman.commands.ServerCommand;

/**
 * Created with IntelliJ IDEA.
 * User: fedepaol
 * Date: 12/16/12
 * Time: 5:11 PM
 */
public class SampleCommand extends ServerCommand {
    String mName;

    @Override
    public void execute(Context c) {
        Log.d("fava", mName);
        //TODO Autogenerated
    }

    @Override
    public int describeContents() {
        return 0;  //TODO Autogenerated
    }

    @Override
    public void writeToParcel(Parcel parcel, int i) {
        parcel.writeString(mName);
    }

    public SampleCommand(String name) {
        mName = name;
    }

    private SampleCommand(Parcel in) {
        mName = in.readString();

    }

    public static final Parcelable.Creator<SampleCommand> CREATOR
            = new Parcelable.Creator<SampleCommand>() {
        public SampleCommand createFromParcel(Parcel in) {
            return new SampleCommand(in);
        }

        public SampleCommand[] newArray(int size) {
            return new SampleCommand[size];
        }
    };
}
