package com.whiterabbit.postmanlibsample;

import android.content.Context;
import android.os.Parcel;
import android.os.Parcelable;
import com.whiterabbit.postman.commands.RestServerCommand;
import com.whiterabbit.postman.commands.ResultParseException;

/**
 * Created with IntelliJ IDEA.
 * User: fedepaol
 * Date: 12/18/12
 * Time: 12:41 AM
 */
public class SampleRestCommand extends RestServerCommand{
    private String mUrl;

    protected  Action getAction(){
        return Action.GET;
    }


    public SampleRestCommand(String url){
        mUrl = url;
    }

    @Override
    protected String getUrl(Action a) {
        return mUrl;
    }

    @Override
    protected void processHttpResult(String result, Context context) throws ResultParseException {
        //TODO Autogenerated
    }

    @Override
    protected String[] getParams() {
        return null;
    }

    @Override
    protected String[] getValues() {
        return null;
    }

    @Override
    public int describeContents() {
        return 0;  //TODO Autogenerated
    }

    @Override
    public void writeToParcel(Parcel parcel, int i) {
        parcel.writeString(mUrl);
    }


    public static final Parcelable.Creator<SampleRestCommand> CREATOR
            = new Parcelable.Creator<SampleRestCommand>() {
        public SampleRestCommand createFromParcel(Parcel in) {
            return new SampleRestCommand(in);
        }

        public SampleRestCommand[] newArray(int size) {
            return new SampleRestCommand[size];
        }
    };


    private SampleRestCommand(Parcel in){
        mUrl = in.readString();

    }
}
