package com.whiterabbit.postmanlibsample;

import android.content.Intent;
import android.os.Bundle;
import android.support.v4.app.FragmentActivity;
import android.view.View;
import android.widget.AdapterView;
import android.widget.ArrayAdapter;
import android.widget.ListView;

/**
 * Created with IntelliJ IDEA.
 * User: fedepaol
 * Date: 1/17/13
 * Time: 9:22 PM
 */
public class SampleList extends FragmentActivity implements AdapterView.OnItemClickListener {
    private ListView mSamples;
    private String[] sampleList = { "Twitter", "NoAuth", "Linkedin", "Facebook"  };

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);    // Autogenerated
        setContentView(R.layout.sample_list);

        mSamples = (ListView) findViewById(R.id.SampleList);

        final ArrayAdapter<String> adp = new ArrayAdapter<String>(this, android.R.layout.simple_list_item_1, sampleList);
        mSamples.setAdapter(adp);
        mSamples.setOnItemClickListener(this);
    }

    @Override
    public void onItemClick(AdapterView<?> adapterView, View view, int i, long l) {
        Intent j;
        switch((int) l){
            case 0:
                j = new Intent(this, TwitterSample.class);
            break;
            case 1:
                j = new Intent(this, NoAuthSample.class);
                break;
            case 2:
                j = new Intent(this, LinkedinSample.class);
            break;
            case 3:
                j = new Intent(this, FacebookSample.class);
            break;
            default:
                return;
        }

        startActivity(j);
    }
}
