package com.whiterabbit.postmanlibsample;

import android.os.Parcel;
import android.os.Parcelable;

/**
 * Created with IntelliJ IDEA.
 * User: fedepaol
 * Date: 12/16/12
 * Time: 5:11 PM
 */
public class User implements Parcelable {
    private String mName;

    @Override
    public int describeContents() {
        return 0;  //TODO Autogenerated
    }

    @Override
    public void writeToParcel(Parcel parcel, int i) {
        //TODO Autogenerated
    }
}
