package com.whiterabbit.postmanlibsample.com.whiterabbit.postmanlibsample.commands;

import android.content.Context;
import android.graphics.Bitmap;
import android.graphics.BitmapFactory;
import android.os.Parcel;
import com.whiterabbit.postman.commands.RestServerCommand;
import com.whiterabbit.postman.exceptions.ResultParseException;
import org.scribe.model.OAuthRequest;
import org.scribe.model.Response;
import org.scribe.model.Verb;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;

/**
 * Created with IntelliJ IDEA.
 * User: fedepaol
 * Date: 12/18/12
 * Time: 12:41 AM
 */
public class NoAuthCommand extends RestServerCommand {
    private static final String url = "http://www.cimonesci.it/cams/polle.jpg";


    public NoAuthCommand(){
        super(Verb.GET, url);
    }

    @Override
    protected void processHttpResult(Response result, Context context) throws ResultParseException {
        Bitmap b = BitmapFactory.decodeStream(result.getStream());
        File path = context.getExternalFilesDir(null);
        File target = new File(path, "picture.png");
        FileOutputStream out = null;
        try {
            out = new FileOutputStream(target);
            b.compress(Bitmap.CompressFormat.PNG, 90, out);
            out.close();
        } catch (FileNotFoundException e) {
            e.printStackTrace();  //To change body of catch statement use File | Settings | File Templates.
        } catch (IOException e) {
            e.printStackTrace();  //To change body of catch statement use File | Settings | File Templates.
        }

    }

    @Override
    protected void addParamsToRequest(OAuthRequest request) {
    }

    @Override
    public int describeContents() {
        return 0;  //TODO Autogenerated
    }



    public static final Creator<NoAuthCommand> CREATOR
            = new Creator<NoAuthCommand>() {
        public NoAuthCommand createFromParcel(Parcel in) {
            return new NoAuthCommand(in);
        }

        public NoAuthCommand[] newArray(int size) {
            return new NoAuthCommand[size];
        }
    };


    public NoAuthCommand(Parcel in){
        super(in);
    }

}
