package com.whiterabbit.postmanlibsample.com.whiterabbit.postmanlibsample.commands;

import android.content.Context;
import android.os.Parcel;
import com.whiterabbit.postman.commands.RestServerCommand;
import com.whiterabbit.postman.exceptions.ResultParseException;
import com.whiterabbit.postmanlibsample.StoreUtils;
import org.codehaus.jackson.JsonNode;
import org.codehaus.jackson.map.ObjectMapper;
import org.scribe.model.OAuthRequest;
import org.scribe.model.Response;
import org.scribe.model.Verb;

import java.io.IOException;

/**
 * Created with IntelliJ IDEA.
 * User: fedepaol
 * Date: 12/18/12
 * Time: 12:41 AM
 */
public class TwitterGetLatestTweetCommand extends RestServerCommand {
    private static final String url = "https://api.twitter.com/1.1/statuses/home_timeline.json";


    public TwitterGetLatestTweetCommand(){
        super(Verb.GET, url);
    }

    @Override
    protected void processHttpResult(Response result, Context context) throws ResultParseException {
        ObjectMapper mapper = new ObjectMapper();
        try {
            JsonNode root = mapper.readTree(result.getBody());
            for (JsonNode tweet : root){
                String text = tweet.path("text").toString();
                String user = tweet.path("user").path("name").toString();

                StoreUtils.setLatestTweet(String.format("%s -> %s", user, text), context);
            }
        } catch (IOException e) {
            notifyError("Failed to parse response", context);
        }

    }

    @Override
    protected void addParamsToRequest(OAuthRequest request) {
        request.addQuerystringParameter("count", "1");
    }

    @Override
    public int describeContents() {
        return 0;  //TODO Autogenerated
    }



    public static final Creator<TwitterGetLatestTweetCommand> CREATOR
            = new Creator<TwitterGetLatestTweetCommand>() {
        public TwitterGetLatestTweetCommand createFromParcel(Parcel in) {
            return new TwitterGetLatestTweetCommand(in);
        }

        public TwitterGetLatestTweetCommand[] newArray(int size) {
            return new TwitterGetLatestTweetCommand[size];
        }
    };


    public TwitterGetLatestTweetCommand(Parcel in){
        super(in);
    }

}
