package com.whiterabbit.postmanlibsample;

import android.content.Context;
import android.os.Parcel;
import android.os.Parcelable;
import com.whiterabbit.postman.commands.RestServerCommand;
import com.whiterabbit.postman.commands.ResultParseException;
import org.scribe.model.OAuthRequest;
import org.scribe.model.Response;
import org.scribe.model.Verb;

/**
 * Created with IntelliJ IDEA.
 * User: fedepaol
 * Date: 12/18/12
 * Time: 12:41 AM
 */
public class SampleRestCommand extends RestServerCommand {


    public SampleRestCommand(String url){
        super(Verb.GET, url);
    }

    @Override
    protected void processHttpResult(Response result, Context context) throws ResultParseException {
        //TODO Autogenerated
    }

    @Override
    protected void addParamsToRequest(OAuthRequest request) {
        //TODO Autogenerated
    }

    @Override
    public int describeContents() {
        return 0;  //TODO Autogenerated
    }



    public static final Parcelable.Creator<SampleRestCommand> CREATOR
            = new Parcelable.Creator<SampleRestCommand>() {
        public SampleRestCommand createFromParcel(Parcel in) {
            return new SampleRestCommand(in);
        }

        public SampleRestCommand[] newArray(int size) {
            return new SampleRestCommand[size];
        }
    };


    public SampleRestCommand(Parcel in){
        super(in);
    }

}
